# Generated by Django 3.1.7 on 2021-04-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='doctors_images')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(default='', max_length=10)),
                ('degree', models.CharField(max_length=40)),
                ('fees', models.CharField(max_length=8)),
                ('hospital_address', models.CharField(max_length=150, null=True)),
                ('specializatioin', models.CharField(max_length=40, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('telephone_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=30, unique=True)),
                ('payment_number', models.CharField(max_length=15)),
                ('emergency_charge', models.CharField(max_length=15)),
                ('achievements', models.CharField(max_length=300, null=True)),
                ('username', models.CharField(max_length=18, unique=True)),
                ('password', models.CharField(max_length=14, unique=True)),
            ],
        ),
    ]
