# Generated by Django 3.1.7 on 2021-05-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0002_auto_20210510_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_Complain',
            new_name='user_Complaint',
        ),
        migrations.AddField(
            model_name='contact',
            name='user_rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
