# Generated by Django 3.1.7 on 2021-05-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0003_auto_20210511_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_Complaint',
            new_name='user_complaint',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_suggesstion',
            new_name='user_suggestion',
        ),
    ]
