# Generated by Django 3.1.7 on 2021-06-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0005_doctor_average_time_per_patient_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointmet_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('emergency', models.CharField(max_length=10, null=True)),
                ('confirmation_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=14),
        ),
    ]
