# Generated by Django 3.1.7 on 2021-06-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0006_auto_20210608_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='d_id',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
