# Generated by Django 3.1.7 on 2021-06-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0007_appointments_d_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='dateTime',
            field=models.CharField(default='12-5-2021 , 0:00Am', max_length=30),
        ),
    ]
