# Generated by Django 3.1.7 on 2021-06-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0008_appointments_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='case_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='dateTime',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
