# Generated by Django 3.1.7 on 2021-06-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0009_auto_20210620_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='case_type',
        ),
        migrations.AddField(
            model_name='appointments',
            name='confirm_case',
            field=models.BooleanField(default=False),
        ),
    ]
