# Generated by Django 3.1.7 on 2021-06-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0010_auto_20210622_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='confirm_case',
            field=models.BooleanField(default=True),
        ),
    ]
