# Generated by Django 3.1.7 on 2021-06-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0011_auto_20210622_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appointmet_id',
            new_name='id',
        ),
    ]
