# Generated by Django 3.1.7 on 2021-06-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0013_auto_20210624_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='age',
            field=models.PositiveIntegerField(default='18'),
        ),
    ]
