# Generated by Django 3.1.7 on 2021-07-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0015_auto_20210626_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='confirm_case',
            field=models.CharField(default='No', max_length=5),
        ),
    ]
