# Generated by Django 3.1.7 on 2021-07-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0016_auto_20210703_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='confirm_case',
            field=models.CharField(default='no', max_length=5),
        ),
    ]
