# Generated by Django 3.1.7 on 2021-07-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0019_auto_20210719_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='confirm',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
