# Generated by Django 3.2.8 on 2021-10-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0020_auto_20210721_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
