# Generated by Django 3.1.7 on 2022-03-10 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('am', '0025_delete_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
