# Generated by Django 3.1.7 on 2022-04-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am', '0027_doctor_clinic_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='average_time_per_patient_minute',
            field=models.CharField(default='30', max_length=4),
        ),
    ]
